{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreKind }}
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.externalSecret.targetName }}
  data:
  {{- toYaml .Values.externalSecret.data | nindent 2 }}
{{- end }}
