apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSzBpVm5wOVc0QTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01qQXdNRFV5TWpCYUZ3MHpOVEV3TVRnd01EVTNNakJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNyY2tLeHNnci9jRnBwYjRzOFlrVWJwWnVaK01zdHQ0TDA0MVNDSWhxZFc5NDlKb3ZIS2hwemo5SksKT1VyK3RwY2VuK1c4eFJFZkZlNGNnSG9QQ0l0SFBGWnhOYW52WGs0TWVaUUp4V0pOS3lLWU9lMjFJeE9pUUhlVQpFdzZvVWxOWmp0N2xRV2t5VWtIN3QvbUMzWnFRb1B6NFpEazYrVW1vbEJOaFNNUUR1QW9kcHBrY1RuTWNSOWlhCnFMN1RpVUhzZWoxNGRhV2RyUVZ5WnZDdGFDU04yVGNaWWJQMGlrMDJOQnVBd1NhUkxxRHJ4bm1FQ2d6a0RIUlIKUlFGMWEyY2l4dWtMS0g4SWtudXQzeURQT1psYkxWSXMzSGtULzZpb090YkpudElraDhEaEk0aUVNb0ZsekFRUQpyVTRtQWlIMkRWU0FUbStLRE5IZ1RqTHpaTTJKQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUbzI0cDNUOEZaQzdQdzFBd3h4VGNITXErNHl6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0hTOGNMbTBreQplRFhCNVhCNlBpSFBuZXdLeVFLeFkrS3grV2lOQWlQK3o2aEpDV05jTTZGV2FYOUZNRnRKR29OV1Jza3g5T01KCnlvY2x3SXFuQ21zRHZnVlVYSnVBUEVMV2Y5djlFUkpBYjNmTDdNd2RZbGNpMVVCZGV5T0x0TTdsQkZEWXRNbjAKbTF4UXl5TXhkNTkrUXg5ZEs5clZ6N3FHSjJQSFQxVnU4cmxpdko5ekZJUDJDb1N3WDBvbmRBdnJlck5FbXFaOAozalJwbldqM2xVVTNSL0NFdGg2U1pJQzdvV2FzeHNCcytYd1VjQk56djR3Y2VrK2JSMXBIeXVaUHhvTlMxakY1ClBSWHptcC8xSjJxQmFValVmRnZKSFYwd3h1OGtzU2QveHZMZHhHSXVwdWh3K21FK3BXNU1KUjNiWjFRbS9CbUsKVWFrc2s3RlUxNzdlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5C6FF9ABB017660F2BE682D6221D90B8.gr7.us-east-2.eks.amazonaws.com
  name: remed-dev-eks
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSzBpVm5wOVc0QTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01qQXdNRFV5TWpCYUZ3MHpOVEV3TVRnd01EVTNNakJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNyY2tLeHNnci9jRnBwYjRzOFlrVWJwWnVaK01zdHQ0TDA0MVNDSWhxZFc5NDlKb3ZIS2hwemo5SksKT1VyK3RwY2VuK1c4eFJFZkZlNGNnSG9QQ0l0SFBGWnhOYW52WGs0TWVaUUp4V0pOS3lLWU9lMjFJeE9pUUhlVQpFdzZvVWxOWmp0N2xRV2t5VWtIN3QvbUMzWnFRb1B6NFpEazYrVW1vbEJOaFNNUUR1QW9kcHBrY1RuTWNSOWlhCnFMN1RpVUhzZWoxNGRhV2RyUVZ5WnZDdGFDU04yVGNaWWJQMGlrMDJOQnVBd1NhUkxxRHJ4bm1FQ2d6a0RIUlIKUlFGMWEyY2l4dWtMS0g4SWtudXQzeURQT1psYkxWSXMzSGtULzZpb090YkpudElraDhEaEk0aUVNb0ZsekFRUQpyVTRtQWlIMkRWU0FUbStLRE5IZ1RqTHpaTTJKQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUbzI0cDNUOEZaQzdQdzFBd3h4VGNITXErNHl6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0hTOGNMbTBreQplRFhCNVhCNlBpSFBuZXdLeVFLeFkrS3grV2lOQWlQK3o2aEpDV05jTTZGV2FYOUZNRnRKR29OV1Jza3g5T01KCnlvY2x3SXFuQ21zRHZnVlVYSnVBUEVMV2Y5djlFUkpBYjNmTDdNd2RZbGNpMVVCZGV5T0x0TTdsQkZEWXRNbjAKbTF4UXl5TXhkNTkrUXg5ZEs5clZ6N3FHSjJQSFQxVnU4cmxpdko5ekZJUDJDb1N3WDBvbmRBdnJlck5FbXFaOAozalJwbldqM2xVVTNSL0NFdGg2U1pJQzdvV2FzeHNCcytYd1VjQk56djR3Y2VrK2JSMXBIeXVaUHhvTlMxakY1ClBSWHptcC8xSjJxQmFValVmRnZKSFYwd3h1OGtzU2QveHZMZHhHSXVwdWh3K21FK3BXNU1KUjNiWjFRbS9CbUsKVWFrc2s3RlUxNzdlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5C6FF9ABB017660F2BE682D6221D90B8.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:828862865943:cluster/remed-dev-eks
contexts:
- context:
    cluster: remed-dev-eks
    user: remed-dev-eks
  name: remed-dev-eks
- context:
    cluster: arn:aws:eks:us-east-2:828862865943:cluster/remed-dev-eks
    user: arn:aws:eks:us-east-2:828862865943:cluster/remed-dev-eks
  name: arn:aws:eks:us-east-2:828862865943:cluster/remed-dev-eks
current-context: arn:aws:eks:us-east-2:828862865943:cluster/remed-dev-eks
kind: Config
users:
- name: remed-dev-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - remed-dev-eks
      - --region
      - us-east-2
      command: aws
- name: arn:aws:eks:us-east-2:828862865943:cluster/remed-dev-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - remed-dev-eks
      - --output
      - json
      command: aws
